<img src = "https://hacktiv8.com/assets/img/logos/hacktiv8-text-black.svg" width = 400>
<h1 align=center><font size = 5>Hacktiv8-Online Python For Data Science // Data Agregate on Transaction Datasets</font></h1>

## Data Preparation

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('googleplaystore.csv')

print ('Data read into a pandas dataframe!')

Data read into a pandas dataframe!

In [3]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
df.shape

(10841, 13)

In [5]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(6)

                Total   Percent
Rating           1474  0.135965
Current Ver         8  0.000738
Android Ver         3  0.000277
Content Rating      1  0.000092
Type                1  0.000092
Last Updated        0  0.000000

In [6]:
df.dropna(how ='any', inplace = True)

In [7]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(6)

                Total  Percent
Android Ver         0      0.0
Current Ver         0      0.0
Last Updated        0      0.0
Genres              0      0.0
Content Rating      0      0.0
Price               0      0.0

In [8]:
df.shape

(9360, 13)

In [37]:
print( len(df['Category'].unique()) , "categories")

print("\n", df['Category'].unique())

33 categories

 ['ART_AND_DESIGN' 'AUTO_AND_VEHICLES' 'BEAUTY' 'BOOKS_AND_REFERENCE'
 'BUSINESS' 'COMICS' 'COMMUNICATION' 'DATING' 'EDUCATION' 'ENTERTAINMENT'
 'EVENTS' 'FINANCE' 'FOOD_AND_DRINK' 'HEALTH_AND_FITNESS' 'HOUSE_AND_HOME'
 'LIBRARIES_AND_DEMO' 'LIFESTYLE' 'GAME' 'FAMILY' 'MEDICAL' 'SOCIAL'
 'SHOPPING' 'PHOTOGRAPHY' 'SPORTS' 'TRAVEL_AND_LOCAL' 'TOOLS'
 'PERSONALIZATION' 'PRODUCTIVITY' 'PARENTING' 'WEATHER' 'VIDEO_PLAYERS'
 'NEWS_AND_MAGAZINES' 'MAPS_AND_NAVIGATION']

In [38]:
print( len(df['Genres'].unique()) , "genres")

print("\n", df['Genres'].unique())

115 genres

 ['Art & Design' 'Art & Design;Pretend Play' 'Art & Design;Creativity'
 'Auto & Vehicles' 'Beauty' 'Books & Reference' 'Business' 'Comics'
 'Comics;Creativity' 'Communication' 'Dating' 'Education;Education'
 'Education' 'Education;Creativity' 'Education;Music & Video'
 'Education;Action & Adventure' 'Education;Pretend Play'
 'Education;Brain Games' 'Entertainment' 'Entertainment;Music & Video'
 'Entertainment;Brain Games' 'Entertainment;Creativity' 'Events' 'Finance'
 'Food & Drink' 'Health & Fitness' 'House & Home' 'Libraries & Demo'
 'Lifestyle' 'Lifestyle;Pretend Play' 'Adventure;Action & Adventure'
 'Arcade' 'Casual' 'Card' 'Casual;Pretend Play' 'Action' 'Strategy'
 'Puzzle' 'Sports' 'Music' 'Word' 'Racing' 'Casual;Creativity'
 'Casual;Action & Adventure' 'Simulation' 'Adventure' 'Board' 'Trivia'
 'Role Playing' 'Simulation;Education' 'Action;Action & Adventure'
 'Casual;Brain Games' 'Simulation;Action & Adventure'
 'Educational;Creativity' 'Puzzle;Brain Games' 'Educational;Education'
 'Card;Brain Games' 'Educational;Brain Games' 'Educational;Pretend Play'
 'Entertainment;Education' 'Casual;Education' 'Music;Music & Video'
 'Racing;Action & Adventure' 'Arcade;Pretend Play'
 'Role Playing;Action & Adventure' 'Simulation;Pretend Play'
 'Puzzle;Creativity' 'Sports;Action & Adventure'
 'Educational;Action & Adventure' 'Arcade;Action & Adventure'
 'Entertainment;Action & Adventure' 'Puzzle;Action & Adventure'
 'Strategy;Action & Adventure' 'Music & Audio;Music & Video'
 'Health & Fitness;Education' 'Adventure;Education' 'Board;Brain Games'
 'Board;Action & Adventure' 'Board;Pretend Play' 'Casual;Music & Video'
 'Role Playing;Pretend Play' 'Entertainment;Pretend Play'
 'Video Players & Editors;Creativity' 'Card;Action & Adventure' 'Medical'
 'Social' 'Shopping' 'Photography' 'Travel & Local'
 'Travel & Local;Action & Adventure' 'Tools' 'Tools;Education'
 'Personalization' 'Productivity' 'Parenting' 'Parenting;Music & Video'
 'Parenting;Brain Games' 'Parenting;Education' 'Weather'
 'Video Players & Editors' 'Video Players & Editors;Music & Video'
 'News & Magazines' 'Maps & Navigation'
 'Health & Fitness;Action & Adventure' 'Educational' 'Casino'
 'Adventure;Brain Games' 'Lifestyle;Education'
 'Books & Reference;Education' 'Puzzle;Education'
 'Role Playing;Brain Games' 'Strategy;Education' 'Racing;Pretend Play'
 'Communication;Creativity' 'Strategy;Creativity']

In [11]:
df.Type.unique()

array(['Free', 'Paid'], dtype=object)

## Highest and Lowest Apps

In [12]:
apps_paid=df[df['Type']=='Paid']

In [13]:
apps_paid.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,$4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,$4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,$3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up

In [39]:
apps_paid.Price = apps_paid.Price.apply(lambda x: x.replace('$',''))
apps_paid['Price'] = apps_paid['Price'].apply(lambda x: float(x))

/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5302: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [40]:
apps_paid.Price.max()

400.0

In [44]:
apps_paid[apps_paid['Price'] == 400]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4367,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.3M,"10,000+",Paid,400.0,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up

Apps with highest price

In [41]:
apps_paid.sort_values('Price',ascending=False).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4367,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.3M,"10,000+",Paid,400.00,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up
5356,I Am Rich Premium,FINANCE,4.1,1867,4.7M,"50,000+",Paid,399.99,Everyone,Finance,"November 12, 2017",1.6,4.0 and up
4362,💎 I'm rich,LIFESTYLE,3.8,718,26M,"10,000+",Paid,399.99,Everyone,Lifestyle,"March 11, 2018",1.0.0,4.4 and up
5364,I am rich (Most expensive app),FINANCE,4.1,129,2.7M,"1,000+",Paid,399.99,Teen,Finance,"December 6, 2017",2,4.0.3 and up
4197,most expensive app (H),FAMILY,4.3,6,1.5M,100+,Paid,399.99,Everyone,Entertainment,"July 16, 2018",1.0,7.0 and up
5362,I Am Rich Pro,FAMILY,4.4,201,2.7M,"5,000+",Paid,399.99,Everyone,Entertainment,"May 30, 2017",1.54,1.6 and up
5373,I AM RICH PRO PLUS,FINANCE,4.0,36,41M,"1,000+",Paid,399.99,Everyone,Finance,"June 25, 2018",1.0.2,4.1 and up
5359,I am rich(premium),FINANCE,3.5,472,965k,"5,000+",Paid,399.99,Everyone,Finance,"May 1, 2017",3.4,4.4 and up
5358,I am Rich!,FINANCE,3.8,93,22M,"1,000+",Paid,399.99,Everyone,Finance,"December 11, 2017",1.0,4.1 and up
5351,I am rich,LIFESTYLE,3.8,3547,1.8M,"100,000+",Paid,399.99,Everyone,Lifestyle,"January 12, 2018",2.0,4.0.3 and up

In [42]:
apps_paid.sort_values('Price',ascending=True).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5777,F05WatchFace for Android Wear,PRODUCTIVITY,3.9,127,5.9M,"1,000+",Paid,0.99,Everyone,Productivity,"December 24, 2017",7.0.1,4.3 and up
4003,Neon Glow C - Icon Pack,PERSONALIZATION,4.8,557,74M,"10,000+",Paid,0.99,Everyone,Personalization,"July 27, 2018",4.5.0,4.0.3 and up
10035,Deus Ex GO,FAMILY,4.5,9699,23M,"100,000+",Paid,0.99,Teen,Puzzle,"July 23, 2018",2.1.111374,4.2 and up
4034,Hitman Sniper,GAME,4.6,408292,29M,"10,000,000+",Paid,0.99,Mature 17+,Action,"July 12, 2018",1.7.110758,4.1 and up
4047,Koi Live Wallpaper,PERSONALIZATION,4.6,14026,12M,"100,000+",Paid,0.99,Everyone,Personalization,"June 24, 2014",1.9,2.2 and up
8993,DW Contacts widget,TOOLS,4.3,56,2.0M,"1,000+",Paid,0.99,Everyone,Tools,"June 5, 2014",1.1.0.0,2.1 and up
5557,Nightenfell: Shared AR,GAME,4.5,20,65M,"1,000+",Paid,0.99,Everyone 10+,Action,"March 27, 2018",1.0.0,7.0 and up
4169,Go,PERSONALIZATION,4.6,89,11M,"5,000+",Paid,0.99,Everyone,Personalization,"October 21, 2017",1.6.1,4.0.3 and up
10039,Device Info Ex Live Wallpaper,PERSONALIZATION,4.1,2645,1.1M,"50,000+",Paid,0.99,Everyone,Personalization,"December 20, 2015",11.0.0,2.1 and up
6584,iBP Blood Pressure,MEDICAL,4.4,578,704k,"10,000+",Paid,0.99,Everyone,Medical,"November 30, 2014",7.0.1,2.2 and up

## Category in Total

In [17]:
data_category = df.groupby('Category').count()

In [18]:
data_category

,App,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
Category,,,,,,,,,,,,
ART_AND_DESIGN,61,61,61,61,61,61,61,61,61,61,61,61
AUTO_AND_VEHICLES,73,73,73,73,73,73,73,73,73,73,73,73
BEAUTY,42,42,42,42,42,42,42,42,42,42,42,42
BOOKS_AND_REFERENCE,178,178,178,178,178,178,178,178,178,178,178,178
BUSINESS,303,303,303,303,303,303,303,303,303,303,303,303
COMICS,58,58,58,58,58,58,58,58,58,58,58,58
COMMUNICATION,328,328,328,328,328,328,328,328,328,328,328,328
DATING,195,195,195,195,195,195,195,195,195,195,195,195
EDUCATION,155,155,155,155,155,155,155,155,155,155,155,155
ENTERTAINMENT,149,149,149,149,149,149,149,149,149,149,149,149
EVENTS,45,45,45,45,45,45,45,45,45,45,45,45
FAMILY,1746,1746,1746,1746,1746,1746,1746,1746,1746,1746,1746,1746
FINANCE,323,323,323,323,323,323,323,323,323,323,323,323
FOOD_AND_DRINK,109,109,109,109,109,109,109,109,109,109,109,109
GAME,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097
HEALTH_AND_FITNESS,297,297,297,297,297,297,297,297,297,297,297,297
HOUSE_AND_HOME,76,76,76,76,76,76,76,76,76,76,76,76
LIBRARIES_AND_DEMO,64,64,64,64,64,64,64,64,64,64,64,64
LIFESTYLE,314,314,314,314,314,314,314,314,314,314,314,314
MAPS_AND_NAVIGATION,124,124,124,124,124,124,124,124,124,124,124,124
MEDICAL,350,350,350,350,350,350,350,350,350,350,350,350
NEWS_AND_MAGAZINES,233,233,233,233,233,233,233,233,233,233,233,233
PARENTING,50,50,50,50,50,50,50,50,50,50,50,50
PERSONALIZATION,312,312,312,312,312,312,312,312,312,312,312,312
PHOTOGRAPHY,317,317,317,317,317,317,317,317,317,317,317,317
PRODUCTIVITY,351,351,351,351,351,351,351,351,351,351,351,351
SHOPPING,238,238,238,238,238,238,238,238,238,238,238,238
SOCIAL,259,259,259,259,259,259,259,259,259,259,259,259
SPORTS,319,319,319,319,319,319,319,319,319,319,319,319
TOOLS,733,733,733,733,733,733,733,733,733,733,733,733
TRAVEL_AND_LOCAL,226,226,226,226,226,226,226,226,226,226,226,226
VIDEO_PLAYERS,160,160,160,160,160,160,160,160,160,160,160,160
WEATHER,75,75,75,75,75,75,75,75,75,75,75,75

In [19]:
df_category = df.Category.value_counts().reset_index().rename(columns={'index': 'Category', 'Category': 'Count'})

In [20]:
df_category.sort_values('Count',ascending=False)

               Category  Count
0                FAMILY   1746
1                  GAME   1097
2                 TOOLS    733
3          PRODUCTIVITY    351
4               MEDICAL    350
5         COMMUNICATION    328
6               FINANCE    323
7                SPORTS    319
8           PHOTOGRAPHY    317
9             LIFESTYLE    314
10      PERSONALIZATION    312
11             BUSINESS    303
12   HEALTH_AND_FITNESS    297
13               SOCIAL    259
14             SHOPPING    238
15   NEWS_AND_MAGAZINES    233
16     TRAVEL_AND_LOCAL    226
17               DATING    195
18  BOOKS_AND_REFERENCE    178
19        VIDEO_PLAYERS    160
20            EDUCATION    155
21        ENTERTAINMENT    149
22  MAPS_AND_NAVIGATION    124
23       FOOD_AND_DRINK    109
24       HOUSE_AND_HOME     76
25              WEATHER     75
26    AUTO_AND_VEHICLES     73
27   LIBRARIES_AND_DEMO     64
28       ART_AND_DESIGN     61
29               COMICS     58
30            PARENTING     50
31               EVENTS     45
32               BEAUTY     42

In [21]:
df_category

               Category  Count
0                FAMILY   1746
1                  GAME   1097
2                 TOOLS    733
3          PRODUCTIVITY    351
4               MEDICAL    350
5         COMMUNICATION    328
6               FINANCE    323
7                SPORTS    319
8           PHOTOGRAPHY    317
9             LIFESTYLE    314
10      PERSONALIZATION    312
11             BUSINESS    303
12   HEALTH_AND_FITNESS    297
13               SOCIAL    259
14             SHOPPING    238
15   NEWS_AND_MAGAZINES    233
16     TRAVEL_AND_LOCAL    226
17               DATING    195
18  BOOKS_AND_REFERENCE    178
19        VIDEO_PLAYERS    160
20            EDUCATION    155
21        ENTERTAINMENT    149
22  MAPS_AND_NAVIGATION    124
23       FOOD_AND_DRINK    109
24       HOUSE_AND_HOME     76
25              WEATHER     75
26    AUTO_AND_VEHICLES     73
27   LIBRARIES_AND_DEMO     64
28       ART_AND_DESIGN     61
29               COMICS     58
30            PARENTING     50
31               EVENTS     45
32               BEAUTY     42

## Most Downloaded Apps

In [22]:
df.Installs.replace('[\+,]', '', regex=True, inplace=True)

In [45]:
df['Installs'].unique()

array(['10000', '500000', '5000000', '50000000', '100000', '50000',
       '1000000', '10000000', '5000', '100000000', '1000000000', '1000',
       '500000000', '100', '500', '10', '5', '50', '1'], dtype=object)

In [24]:
df.sort_values('Installs',ascending=False).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4676,Viber Messenger,COMMUNICATION,4.3,11335481,Varies with device,500000000,Free,0,Everyone,Communication,"July 18, 2018",Varies with device,Varies with device
1908,My Talking Tom,GAME,4.5,14892469,Varies with device,500000000,Free,0,Everyone,Casual,"July 19, 2018",4.8.0.132,4.1 and up
1842,Candy Crush Saga,GAME,4.4,22429716,74M,500000000,Free,0,Everyone,Casual,"July 5, 2018",1.129.0.2,4.1 and up
2546,Facebook Lite,SOCIAL,4.3,8606259,Varies with device,500000000,Free,0,Teen,Social,"August 1, 2018",Varies with device,Varies with device
1885,Pou,GAME,4.3,10486018,24M,500000000,Free,0,Everyone,Casual,"May 25, 2018",1.4.77,4.0 and up
1886,Temple Run 2,GAME,4.3,8119151,62M,500000000,Free,0,Everyone,Action,"July 5, 2018",1.49.1,4.0 and up
465,imo free video calls and chat,COMMUNICATION,4.3,4785988,11M,500000000,Free,0,Everyone,Communication,"June 8, 2018",9.8.000000010501,4.0 and up
347,imo free video calls and chat,COMMUNICATION,4.3,4785892,11M,500000000,Free,0,Everyone,Communication,"June 8, 2018",9.8.000000010501,4.0 and up
467,Viber Messenger,COMMUNICATION,4.3,11335255,Varies with device,500000000,Free,0,Everyone,Communication,"July 18, 2018",Varies with device,Varies with device
1729,Temple Run 2,GAME,4.3,8118937,62M,500000000,Free,0,Everyone,Action,"July 5, 2018",1.49.1,4.0 and up

## Mean of Rating Each Category

In [25]:
df.groupby('Category').mean()

                       Rating
Category
ART_AND_DESIGN       4.377049
AUTO_AND_VEHICLES    4.190411
BEAUTY               4.278571
BOOKS_AND_REFERENCE  4.346067
BUSINESS             4.121452
COMICS               4.155172
COMMUNICATION        4.158537
DATING               3.970769
EDUCATION            4.389032
ENTERTAINMENT        4.126174
EVENTS               4.435556
FAMILY               4.192383
FINANCE              4.131889
FOOD_AND_DRINK       4.166972
GAME                 4.286326
HEALTH_AND_FITNESS   4.277104
HOUSE_AND_HOME       4.197368
LIBRARIES_AND_DEMO   4.179688
LIFESTYLE            4.094904
MAPS_AND_NAVIGATION  4.051613
MEDICAL              4.189143
NEWS_AND_MAGAZINES   4.132189
PARENTING            4.300000
PERSONALIZATION      4.335256
PHOTOGRAPHY          4.192114
PRODUCTIVITY         4.211396
SHOPPING             4.259664
SOCIAL               4.255598
SPORTS               4.223511
TOOLS                4.047203
TRAVEL_AND_LOCAL     4.109292
VIDEO_PLAYERS        4.063750
WEATHER              4.244000

## Genre in Total

In [26]:
data_genre = df.groupby('Genres').count()

In [27]:
data_genre

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Last Updated,Current Ver,Android Ver
Genres,,,,,,,,,,,,
Action,358,358,358,358,358,358,358,358,358,358,358,358
Action;Action & Adventure,17,17,17,17,17,17,17,17,17,17,17,17
Adventure,73,73,73,73,73,73,73,73,73,73,73,73
Adventure;Action & Adventure,13,13,13,13,13,13,13,13,13,13,13,13
Adventure;Brain Games,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
Video Players & Editors,158,158,158,158,158,158,158,158,158,158,158,158
Video Players & Editors;Creativity,2,2,2,2,2,2,2,2,2,2,2,2
Video Players & Editors;Music & Video,3,3,3,3,3,3,3,3,3,3,3,3
Weather,75,75,75,75,75,75,75,75,75,75,75,75
Word,28,28,28,28,28,28,28,28,28,28,28,28

In [28]:
df_genre = df.Genres.value_counts().reset_index().rename(columns={'index': 'Genres', 'Genres': 'Count'})

In [29]:
df_genre

                                  Genres  Count
0                                  Tools    732
1                          Entertainment    533
2                              Education    468
3                                 Action    358
4                           Productivity    351
..                                   ...    ...
110           Health & Fitness;Education      1
111  Health & Fitness;Action & Adventure      1
112                   Board;Pretend Play      1
113                Adventure;Brain Games      1
114                     Card;Brain Games      1

[115 rows x 2 columns]

In [30]:
df_genre.sort_values('Count', ascending=False)

                       Genres  Count
0                       Tools    732
1               Entertainment    533
2                   Education    468
3                      Action    358
4                Productivity    351
..                        ...    ...
98        Strategy;Creativity      1
97          Comics;Creativity      1
96   Communication;Creativity      1
95      Parenting;Brain Games      1
114          Card;Brain Games      1

[115 rows x 2 columns]

## DA for Genres

In [31]:
df.groupby('Genres').describe()

                                      Rating                                 \
                                       count      mean       std  min   25%
Genres
Action                                 358.0  4.285475  0.291353  3.1  4.20
Action;Action & Adventure               17.0  4.311765  0.172780  3.9  4.30
Adventure                               73.0  4.180822  0.312542  3.4  4.00
Adventure;Action & Adventure            13.0  4.423077  0.148064  4.1  4.50
Adventure;Brain Games                    1.0  4.600000       NaN  4.6  4.60
...                                      ...       ...       ...  ...   ...
Video Players & Editors                158.0  4.063924  0.554566  1.8  3.80
Video Players & Editors;Creativity       2.0  4.100000  0.000000  4.1  4.10
Video Players & Editors;Music & Video    3.0  4.000000  0.000000  4.0  4.00
Weather                                 75.0  4.244000  0.331353  3.3  4.05
Word                                    28.0  4.410714  0.325849  3.8  4.20


                                       50%  75%  max
Genres
Action                                 4.3  4.5  5.0
Action;Action & Adventure              4.3  4.4  4.6
Adventure                              4.3  4.4  4.7
Adventure;Action & Adventure           4.5  4.5  4.5
Adventure;Brain Games                  4.6  4.6  4.6
...                                    ...  ...  ...
Video Players & Editors                4.2  4.4  4.9
Video Players & Editors;Creativity     4.1  4.1  4.1
Video Players & Editors;Music & Video  4.0  4.0  4.0
Weather                                4.3  4.5  4.8
Word                                   4.4  4.7  4.9

[115 rows x 8 columns]

In [32]:
df.groupby('Genres').median()

                                       Rating
Genres
Action                                    4.3
Action;Action & Adventure                 4.3
Adventure                                 4.3
Adventure;Action & Adventure              4.5
Adventure;Brain Games                     4.6
...                                       ...
Video Players & Editors                   4.2
Video Players & Editors;Creativity        4.1
Video Players & Editors;Music & Video     4.0
Weather                                   4.3
Word                                      4.4

[115 rows x 1 columns]

In [33]:
df.groupby('Genres').mean()

                                         Rating
Genres
Action                                 4.285475
Action;Action & Adventure              4.311765
Adventure                              4.180822
Adventure;Action & Adventure           4.423077
Adventure;Brain Games                  4.600000
...                                         ...
Video Players & Editors                4.063924
Video Players & Editors;Creativity     4.100000
Video Players & Editors;Music & Video  4.000000
Weather                                4.244000
Word                                   4.410714

[115 rows x 1 columns]

In [34]:
df.groupby('Category').mean()

                       Rating
Category
ART_AND_DESIGN       4.377049
AUTO_AND_VEHICLES    4.190411
BEAUTY               4.278571
BOOKS_AND_REFERENCE  4.346067
BUSINESS             4.121452
COMICS               4.155172
COMMUNICATION        4.158537
DATING               3.970769
EDUCATION            4.389032
ENTERTAINMENT        4.126174
EVENTS               4.435556
FAMILY               4.192383
FINANCE              4.131889
FOOD_AND_DRINK       4.166972
GAME                 4.286326
HEALTH_AND_FITNESS   4.277104
HOUSE_AND_HOME       4.197368
LIBRARIES_AND_DEMO   4.179688
LIFESTYLE            4.094904
MAPS_AND_NAVIGATION  4.051613
MEDICAL              4.189143
NEWS_AND_MAGAZINES   4.132189
PARENTING            4.300000
PERSONALIZATION      4.335256
PHOTOGRAPHY          4.192114
PRODUCTIVITY         4.211396
SHOPPING             4.259664
SOCIAL               4.255598
SPORTS               4.223511
TOOLS                4.047203
TRAVEL_AND_LOCAL     4.109292
VIDEO_PLAYERS        4.063750
WEATHER              4.244000

In [35]:
df.groupby('Category').agg(pd.Series.mode)

,App,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
Category,,,,,,,,,,,
ART_AND_DESIGN,Textgram - write on photos,4.7,967,100000,Free,0,Everyone,Art & Design,"July 30, 2018",1.0,4.1 and up
AUTO_AND_VEHICLES,"[AE Garage, All of the parking lot - National ...",4.6,"[12, 129, 4, 5]",100000,Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,4.1 and up
BEAUTY,"[AI Face Beauty Analysis - IntelliFace (Free),...",4.7,2,10000,Free,0,Everyone,Beauty,"[April 5, 2018, July 12, 2018, July 24, 2018, ...",1.0,4.0.3 and up
BOOKS_AND_REFERENCE,"[Amazon Kindle, Dictionary - Merriam-Webster, ...",4.5,5,1000,Free,0,Everyone,Books & Reference,"August 1, 2018",Varies with device,4.0 and up
BUSINESS,"[Box, Google Ads, Google My Business, Quick PD...",4.4,2,1000000,Free,0,Everyone,Business,"August 2, 2018",Varies with device,4.1 and up
COMICS,"[DC Comics, Daily Manga - Comic & Webtoon, LIN...",4.4,"[1006, 1010, 1013635, 1013944, 109, 115, 12088...",1000000,Free,0,Everyone,Comics,"July 31, 2018",Varies with device,4.0.3 and up
COMMUNICATION,Viber Messenger,4.3,"[5, 7]",10000000,Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
DATING,"[Adult Dirty Emojis, BBW Dating & Plus Size Ch...",4.1,"[5, 6]",100000,Free,0,Mature 17+,Dating,"[August 1, 2018, July 24, 2018, July 31, 2018]",8.2,4.1 and up
EDUCATION,"[Duolingo: Learn Languages Free, Learn languag...",4.6,211856,1000000,Free,0,Everyone,Education,"August 1, 2018",Varies with device,Varies with device
ENTERTAINMENT,"[Netflix, Nick]",4.2,"[123279, 27424]",1000000,Free,0,Teen,Entertainment,"August 3, 2018",Varies with device,Varies with device
EVENTS,"[AO Player, All Events in City, Arab Halls - F...","[4.6, 5.0]",7,100000,Free,0,Everyone,Events,"[August 3, 2018, July 12, 2018, May 29, 2018]",Varies with device,4.1 and up
FAMILY,ROBLOX,4.3,4,1000000,Free,0,Everyone,Entertainment,"August 2, 2018",1.0,4.1 and up
FINANCE,Google Pay,4.3,4,10000,Free,0,Everyone,Finance,"July 31, 2018",Varies with device,Varies with device
FOOD_AND_DRINK,Chick-fil-A,4.5,"[1032935, 155944, 22875]",1000000,Free,0,Everyone,Food & Drink,"August 1, 2018",Varies with device,Varies with device
GAME,"[8 Ball Pool, Bowmasters, Candy Crush Saga, He...",4.5,"[17, 21, 33, 8]",10000000,Free,0,Everyone,Action,"August 1, 2018",Varies with device,4.1 and up
HEALTH_AND_FITNESS,Calorie Counter - MyFitnessPal,4.6,"[3, 6]",1000000,Free,0,Everyone,Health & Fitness,"July 31, 2018",Varies with device,Varies with device
HOUSE_AND_HOME,Houzz Interior Design Ideas,4.5,"[162243, 175293, 22584, 353813, 36857, 417907,...",1000000,Free,0,Everyone,House & Home,"August 1, 2018",Varies with device,Varies with device
LIBRARIES_AND_DEMO,Cardboard,"[4.1, 4.2, 4.3, 4.4]","[15, 45, 50]",10000,Free,0,Everyone,Libraries & Demo,"February 5, 2017",2.3.2,1.6 and up
LIFESTYLE,Fashion in Vogue,5,"[10, 2, 3]",1000000,Free,0,Everyone,Lifestyle,"August 2, 2018",Varies with device,4.1 and up
MAPS_AND_NAVIGATION,"[Maps & GPS Navigation — OsmAnd, Mapy.cz - Cyc...",4.2,8,1000000,Free,0,Everyone,Maps & Navigation,"[August 3, 2018, July 26, 2018]",Varies with device,4.1 and up
MEDICAL,"[Cardiac diagnosis (heart rate, arrhythmia), H...",4.5,2,1000,Free,0,Everyone,Medical,"July 27, 2018","[1.0, Varies with device]",4.1 and up
NEWS_AND_MAGAZINES,Google News,4.3,"[10, 249919, 293080, 296781, 4, 49259]",1000000,Free,0,Everyone,News & Magazines,"August 3, 2018",Varies with device,4.1 and up
PARENTING,"[Amazon FreeTime – Kids’ Videos, Books, & TV s...","[4.4, 4.7]",39,"[100000, 1000000]",Free,0,Everyone,Parenting,"May 28, 2018",Varies with device,4.0.3 and up
PERSONALIZATION,ZEDGE™ Ringtones & Wallpapers,4.5,"[4, 5]",1000000,Free,0,Everyone,Personalization,"August 3, 2018",1.0,4.0.3 and up
PHOTOGRAPHY,BeautyPlus - Easy Photo Editor & Selfie Camera,"[4.3, 4.4]",1,10000000,Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device
PRODUCTIVITY,"[Evernote – Organizer, Planner for Notes & Mem...",4.4,"[12, 16, 3, 691474, 8]",1000000,Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
SHOPPING,"[Wish - Shopping Made Fun, eBay: Buy & Sell th...",4.5,2788923,10000000,Free,0,Everyone,Shopping,"August 3, 2018",Varies with device,4.1 and up
SOCIAL,MeetMe: Chat & Meet New People,4.3,"[1259894, 3, 3781770, 5]",10000000,Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
SPORTS,"CBS Sports App - Scores, News, Stats & Watch Live",4.4,"[288809, 91031]",5000000,Free,0,Everyone,Sports,"[August 1, 2018, August 2, 2018]",Varies with device,4.1 and up
TOOLS,Gboard - the Google Keyboard,4.3,7,"[10000, 100000, 1000000]",Free,0,Everyone,Tools,"July 30, 2018",Varies with device,4.1 and up
TRAVEL_AND_LOCAL,"[Skyscanner, TripAdvisor Hotels Flights Restau...",4.4,481546,1000000,Free,0,Everyone,Travel & Local,"August 6, 2018",Varies with device,Varies with device
VIDEO_PLAYERS,MX Player,4.3,"[20, 23, 32, 3484, 5639]",1000000,Free,0,Everyone,Video Players & Editors,"August 3, 2018",Varies with device,Varies with device
WEATHER,[AccuWeather: Daily Forecast & Live Weather Re...,4.2,"[100994, 11, 11118, 11297, 115, 11510, 116, 11...",1000000,Free,0,Everyone,Weather,"August 2, 2018",Varies with device,Varies with device

In [46]:
df[['Genres', 'Rating']].groupby(['Genres'], as_index=False).mean()

                                    Genres    Rating
0                                   Action  4.285475
1                Action;Action & Adventure  4.311765
2                                Adventure  4.180822
3             Adventure;Action & Adventure  4.423077
4                    Adventure;Brain Games  4.600000
..                                     ...       ...
110                Video Players & Editors  4.063924
111     Video Players & Editors;Creativity  4.100000
112  Video Players & Editors;Music & Video  4.000000
113                                Weather  4.244000
114                                   Word  4.410714

[115 rows x 2 columns]

In [51]:
df[['Category', 'Rating']].groupby(['Category'], as_index=False).describe()

    Rating
     count      mean       std  min    25%  50%    75%  max
0     61.0  4.377049  0.328326  3.4  4.100  4.4  4.700  5.0
1     73.0  4.190411  0.543692  2.1  4.000  4.3  4.600  4.9
2     42.0  4.278571  0.362603  3.1  4.000  4.3  4.575  4.9
3    178.0  4.346067  0.429046  2.7  4.100  4.5  4.600  5.0
4    303.0  4.121452  0.624422  1.0  3.900  4.3  4.500  5.0
5     58.0  4.155172  0.537758  2.8  3.825  4.4  4.500  5.0
6    328.0  4.158537  0.426192  1.0  4.000  4.3  4.400  5.0
7    195.0  3.970769  0.630510  1.0  3.700  4.1  4.400  5.0
8    155.0  4.389032  0.251894  3.5  4.200  4.4  4.600  4.9
9    149.0  4.126174  0.302556  3.0  3.900  4.2  4.300  4.7
10    45.0  4.435556  0.419499  2.9  4.200  4.5  4.700  5.0
11  1746.0  4.192383  0.508151  1.0  4.000  4.3  4.500  5.0
12   323.0  4.131889  0.642108  1.0  4.000  4.3  4.500  5.0
13   109.0  4.166972  0.548070  1.7  4.000  4.3  4.500  5.0
14  1097.0  4.286326  0.365375  1.0  4.100  4.4  4.500  5.0
15   297.0  4.277104  0.617822  1.4  4.100  4.5  4.600  5.0
16    76.0  4.197368  0.368411  2.8  4.000  4.3  4.500  4.8
17    64.0  4.179688  0.381384  3.1  3.975  4.2  4.400  5.0
18   314.0  4.094904  0.693907  1.5  3.800  4.2  4.600  5.0
19   124.0  4.051613  0.519926  1.9  3.775  4.2  4.400  4.9
20   350.0  4.189143  0.663581  1.0  4.000  4.3  4.600  5.0
21   233.0  4.132189  0.536707  1.7  3.900  4.2  4.500  5.0
22    50.0  4.300000  0.517845  2.0  4.100  4.4  4.675  5.0
23   312.0  4.335256  0.353722  2.5  4.200  4.4  4.600  5.0
24   317.0  4.192114  0.462896  2.0  4.000  4.3  4.500  5.0
25   351.0  4.211396  0.504931  1.0  4.100  4.3  4.500  5.0
26   238.0  4.259664  0.404577  1.6  4.100  4.3  4.500  5.0
27   259.0  4.255598  0.413809  1.9  4.100  4.3  4.500  5.0
28   319.0  4.223511  0.427857  1.5  4.100  4.3  4.500  5.0
29   733.0  4.047203  0.616538  1.0  3.800  4.2  4.400  5.0
30   226.0  4.109292  0.504691  2.2  3.900  4.3  4.400  5.0
31   160.0  4.063750  0.551098  1.8  3.800  4.2  4.400  4.9
32    75.0  4.244000  0.331353  3.3  4.050  4.3  4.500  4.8